# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
        migrations.AlterModelTable(
            name='vip',
            table='vip',
        ),
        migrations.AlterModelTable(
            name='vippermrelstion',
            table='vippermrelstion',
        ),
    ]
