# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='用户 id')),
                ('uid2', models.IntegerField(verbose_name='用户 id')),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者 id')),
                ('sid', models.IntegerField(verbose_name='被滑动者 id')),
                ('stype', models.CharField(choices=[('like', '喜欢'), ('superlike', '超级喜欢'), ('dislike', '不喜欢')], max_length=10, verbose_name='滑动的类型')),
                ('stime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'swiped',
            },
        ),
    ]
