# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_sex', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('unkonwn', '不详')], max_length=18)),
                ('dating_location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('广州', '广州'), ('深圳', '深圳'), ('武汉', '武汉'), ('南京', '南京'), ('西安', '西安'), ('成都', '成都'), ('重庆', '重庆')], max_length=16)),
                ('min_distance', models.IntegerField(default=1)),
                ('max_distance', models.IntegerField(default=10)),
                ('min_dating_age', models.IntegerField(default=16)),
                ('max_dating_age', models.IntegerField(default=45)),
                ('vibration', models.BooleanField(default=True)),
                ('only_matche', models.BooleanField(default=True)),
                ('auto_play', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=16, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('unkonwn', '不详')], max_length=8, verbose_name='性别')),
                ('birthday', models.DateField(default=datetime.date(1990, 10, 1), verbose_name='出生日期')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人形象')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('广州', '广州'), ('深圳', '深圳'), ('武汉', '武汉'), ('南京', '南京'), ('西安', '西安'), ('成都', '成都'), ('重庆', '重庆')], max_length=16, verbose_name='常居地')),
            ],
        ),
    ]
